
spring:
    datasource:
          url: jdbc:mysql://192.168.189.105:3306/user
          username: root
          password: 123
          driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.wfaxxdyy.mall.bean.User


dubbo:
   application:
      name: user-provide
      registry:
        address: zookeeper://127.0.0.1:2181
      protocol:
        name: dubbo
        port: 20880