
spring:
    datasource:
          url: jdbc:mysql://192.168.189.105:3306/user
          username: root
          password: 123
          driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.wfaxxdyy.mall.bean.Product


dubbo:
  application:
    name: product-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql