
spring:
  datasource:
    url: jdbc:mysql://192.168.189.105:3306/user?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wfaxxdyy.mall.bean.CartBean


dubbo:
  application:
    name: order-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882